import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="sticky top-0 z-50 w-full border-b border-slate-800/50 bg-slate-950/70 backdrop-blur-xl px-6 py-4">
          <div className="max-w-5xl mx-auto flex justify-between items-center">
            <Link href="/" className="text-lg font-black text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500 tracking-tight hover:scale-105 transition-transform duration-300">
              NEON 성남
            </Link>
            <div className="flex gap-6 font-mono text-xs uppercase tracking-[0.2em]">
              <Link href="/" className="text-slate-400 hover:text-cyan-400 transition-colors">Home</Link>
              <Link href="/blog" className="text-slate-400 hover:text-cyan-400 transition-colors">Blog</Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
